include:
  # use template for all stages 
  - project: "OE-7035/ssz-da/templates/pipeline-templates"
    ref: v1.1.0
    file: "stages.yml"
  # use template for gitlab pipeline to deploy to shinyapps.io
  - project: "OE-7035/ssz-da/templates/pipeline-templates"
    ref: v1.1.0
    file: "deploy-to-shinyapps.yml"
  # use template for gitlab pipeline to push main to github 
  - project: "OE-7035/ssz-da/templates/pipeline-templates"
    ref: v1.1.0
    file: "publish-to-github.yml"

shiny-deploy-int:
  extends:
    - .shiny-deploy-int
  script:
    - Rscript -e "renv::status()"
    - Rscript -e "source('data-raw/create_latest_data.R')"
    - Rscript -e "source('dev/deploy.R')"

shiny-deploy-prod:
  extends:
    - .shiny-deploy-prod 
  script:
    - Rscript -e "renv::restore()"
    - Rscript -e "source('data-raw/create_latest_data.R')"
    - Rscript -e "source('dev/deploy.R')"

publish-main-to-github:
  extends:
    - .publish-main-to-github
